# Generated by Django 5.2.5 on 2025-11-15 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0002_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='course_details',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
